/* Generated by npm run build. */
const CACHE='cfe-static-8ed2a4a5e319';
const FILES=['./','./index.html','./manifest.webmanifest','./favicon.png'];
async function offline(){const cache=await caches.open(CACHE);await cache.addAll(FILES);}
self.addEventListener('install',e=>{e.waitUntil(offline().then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('cfe-static-')&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{if(e.request.method!=='GET'||new URL(e.request.url).origin!==location.origin)return;e.respondWith(fetch(e.request).then(response=>{if(response.ok){const copy=response.clone();caches.open(CACHE).then(c=>c.put(e.request,copy));}return response;}).catch(async()=>{const cached=await caches.match(e.request);if(cached)return cached;if(e.request.mode==='navigate')return caches.match('./index.html');return Response.error();}));});
self.addEventListener('message',e=>{if(e.data?.type==='CACHE_OFFLINE')e.waitUntil(offline().then(()=>e.ports[0]?.postMessage({ok:true})).catch(()=>e.ports[0]?.postMessage({ok:false})));});
