/* Generated by npm run build. */
const VERSION='e52144705ef6';
const FILES=["./","./index.html","./manifest.webmanifest","./favicon.png"];
const SCOPE=new URL('./',self.location.href).href;
const PREFIX='cfe-static-'+encodeURIComponent(new URL(SCOPE).pathname)+'-';
const CACHE=PREFIX+VERSION;
const PUBLIC_URLS=new Set(FILES.map(file=>new URL(file,SCOPE).href));
async function offline(){const cache=await caches.open(CACHE);await cache.addAll(FILES);}
self.addEventListener('install',e=>{e.waitUntil(offline().then(()=>self.skipWaiting()));});
self.addEventListener('activate',e=>{e.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith(PREFIX)&&k!==CACHE).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',e=>{
 if(e.request.method!=='GET'||!PUBLIC_URLS.has(e.request.url))return;
 e.respondWith(fetch(e.request).then(response=>{
  if(response.ok){const copy=response.clone();e.waitUntil(caches.open(CACHE).then(c=>c.put(e.request,copy)).catch(()=>{}));}
  return response;
 }).catch(async()=>{const cache=await caches.open(CACHE);const cached=await cache.match(e.request);if(cached)return cached;if(e.request.mode==='navigate')return cache.match(new URL('index.html',SCOPE).href);return Response.error();}));
});
self.addEventListener('message',e=>{if(e.data?.type==='CACHE_OFFLINE'&&e.source?.url&&new URL(e.source.url).href.startsWith(SCOPE))e.waitUntil(offline().then(()=>e.ports[0]?.postMessage({ok:true})).catch(()=>e.ports[0]?.postMessage({ok:false})));});
